services:
  example-advanced:
    image: bazel/example/advanced:server_image
    ports:
      - 5000:5000
  example-cookies:
    image: bazel/example/cookies:server_image
    ports:
      - 5001:5000
  integration:
    image: bazel/tests/integration:server_image
    ports:
      - 5003:5000
  example-components:
    image: bazel/example/components:server_image
    ports:
      - 5009:5000
  #  example-simple:
  #    image: bazel/example/simple:server_image
  #  example-remember:
  #    image: bazel/example/remember:server_image
  #  example-hooks:
  #    image: bazel/example/hooks:server_image

  example-mqtt-server:
    image: bazel/example/mqtt:server_image
    environment:
      DB_NAME: /data/db
    volumes:
      - db-volume:/data/
    ports:
      - 5002:5000
  example-mqtt-listener:
    image: bazel/example/mqtt:listener_image
    environment:
      DB_NAME: /data/db
    volumes:
      - db-volume:/data/
    depends_on:
      - broker
      - fluent
  broker:
    image: bazel/example/mqtt:mosquitto
    ports:
      - 9001:9001
      - 1883:1883
  fluent:
    image: bazel/example/mqtt:fluentd
    ports:
      - 24224:24224

volumes:
  db-volume:
